"""azure

Revision ID: 9218bace5f9c
Revises: b6d0b7e17d59
Create Date: 2023-10-27 21:58:28.358782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9218bace5f9c'
down_revision: Union[str, None] = 'b6d0b7e17d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('discharge_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'discharge_time')
    # ### end Alembic commands ###
