"""GCP

Revision ID: b5c9b74f8bc8
Revises: f2ec783b77cf
Create Date: 2023-10-27 22:04:49.670048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c9b74f8bc8'
down_revision: Union[str, None] = 'f2ec783b77cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('discharge_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'discharge_time')
    # ### end Alembic commands ###
